receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: 0.0.0.0:8000
    namespace: otel # appended to metric names with an _ at the end
  sentry:
    dsn: ${SENTRY_DSN}
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # metrics export is not supported by sentry
      # Error Message:
      #   collector server run finished with error: failed to build pipelines:
      #   failed to create "sentry" exporter for data type "metrics":
      #   telemetry type is not supported
      # Also, metrics solution seems to be retired as of Oct 7th
      #  https://docs.sentry.io/platforms/python/metrics/
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [sentry, debug]
